<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    // executor: 执行器函数
    // resolve: 把Promise把状态改为成功态   reject:把状态改为成功态
    // value: 记录成功的原因     reason:记录失败的原因
    // Promise的三个状态 
    // Promise 状态只能改变一次
    const PENDING = 'pending'
    const FULFILLED = 'fulfilled'
    const REJECTED = 'rejected'
    class Promise {
      // 成功的结果
      value
      // 失败的结果
      reason
      // 保存成功的函数
      noFulfilledCallbacks = []
      // 保存失败的函数
      noRejectedCallbacks = []
      // 初始化状态
      status = PENDING
      constructor(executor) {
        // 成功的函数 
        const resolve = (value) => {
          if (this.status === PENDING) {
            this.value = value
            this.status = FULFILLED
            this.noFulfilledCallbacks.forEach(bc => bc())
          }
        }

        // 失败的函数
        const reject = (reason) => {
          if (this.status === PENDING) {
            this.reason = reason
            this.status = REJECTED
            this.noRejectedCallbacks.forEach(bc => bc())
          }
        }

        // 捕获错误并且调用reject
        try {
          executor(resolve, reject)
        } catch (error) {
          reject(error)
        }
      }

      then(noFulfilled, noRejected) {

        const p2 = new Promise((resolve, reject) => {
          // then 成功的回调 并把成功的结果传给then成功的回调
          if (this.status === FULFILLED) {
            // 链式调用时上一次的.then报错时执行reject通知下次.then
            // queueMicrotask() 微任务队列把函数内的内容加入微任务一步队列
            queueMicrotask(() => {
              try {
                let x = noFulfilled(this.value)
                resolve(x)
              } catch (error) {
                reject(error)
              }
            })
          }
          // then 失败的回调 并把失败的结果传给then失败的回调
          if (this.status === REJECTED) {
            queueMicrotask(() => {
              try {
                let x = noRejected(this.reason)
                resolve(x)
              } catch (error) {
                reject(error)
              }
            })
          }
          // 异步函数的处理 先把函数保存起来，等异步函数进行完毕以后，再去相对的成功或者失败的函数内去重新调用
          if (this.status === PENDING) {
            this.noFulfilledCallbacks.push(() => {
              queueMicrotask(() => {
                try {
                  let x = noFulfilled(this.value)
                  resolve(x)
                } catch (error) {
                  reject(error)
                }
              })
            })
            this.noRejectedCallbacks.push(() => {
              queueMicrotask(() => {
                try {
                  let x = noRejected(this.reason)
                  resolve(x)
                } catch (error) {
                  reject(error)
                }
              })
            })
          }
        })
        //  return 一个Promise对象，让实例可以链式调用.then
        return p2
      }

    }
    // then调用
    const p = new Promise((resolve, reject) => {
      // resolve('成功')
      setTimeout(() => {
        resolve('失败')
      }, 3000)
    })
    p.then(
      res => {
        console.log(res);
      },
      err => {
        console.log(err);
      }

    )
  </script>
</body>

</html>